apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ok3cesakt-go
  janus-idp.io/tekton: ok3cesakt-go
  backstage.io/kubernetes-id: ok3cesakt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok3cesakt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
