apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ok3cesakt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ok3cesakt-go 
  name: ok3cesakt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ok3cesakt-go 
