apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ok3cesakt-go 
  janus-idp.io/tekton: ok3cesakt-go
  backstage.io/kubernetes-id: ok3cesakt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok3cesakt-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  